### ISSUE TITLE
CheckMK 2.x installation issue

### ISSUE THREAD

**Issue by 47k** [makanakoeln/projects#8]
OMD[Test]:~$ mkp install /home/user/wsus_sync_status-1.1.mkp
Traceback (most recent call last):
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1674, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1651, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1514, in __init__
    self.firstmember = self.next()
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 2318, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1104, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/omd/sites/Test/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/omd/sites/Test/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\n\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/omd/sites/Test/bin/check_mk", line 92, in <module>
    exit_status = modes.call(mode_name, mode_args, opts, args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/__init__.py", line 69, in call
    return handler(*handler_args)
  File "/omd/sites/Test/lib/python3/cmk/base/modes/check_mk.py", line 654, in mode_packaging
    cmk.base.packaging.do_packaging(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 89, in do_packaging
    f(args)
  File "/omd/sites/Test/lib/python3/cmk/base/packaging.py", line 288, in package_install
    packaging.install_by_path(path)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 352, in install_by_path
    return install(file_object=cast(BinaryIO, f))
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 356, in install
    package = _get_package_info_from_package(file_object)
  File "/omd/sites/Test/lib/python3/cmk/utils/packaging.py", line 490, in _get_package_info_from_package
    tar = tarfile.open(fileobj=file_object, mode="r:gz")
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/omd/sites/Test/lib/python3.8/tarfile.py", line 1678, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

**Comment by gurubert** [comment]
pull request #9 should fix that.

You can download an MKP for checkmk 2.0 here: https://github.com/makanakoeln/check_mk/raw/1cc86a35eae7a5d521c43e1a172eb8f0aea7730e/var/check_mk/packages/wsus_sync_status-2.0.1.mkp
